### ISSUE TITLE
Zone/project styling after clicking "see on map"

### ISSUE THREAD

**Issue by alecburch** [stamen/bluegreenway#131]
after clicking see on map button that is associated with a zone, the zone should be highlighted on the map in some way.

**Comment by ericsoco** [comment]
@almccon tips on how to highlight? (design and implementation. geojson layer? color / fill / stroke / label?)

**Comment by almccon** [comment]
The main thing is that you have to apply a special style if the project has been selected. (and if you're doing a style change on click or mouseover, you have to keep track of the previous (default) style so you can replace it when you mouseout. Or have a function that generates the correct default style.

[Here](https://github.com/stamen/bluegreenway/blob/898b45a30f0cfe36c57f0f0375e2d416e651a215/src/components/LeafletMap.js#L323-L337) I'm setting the style at the time the feature gets created. Here's an example of applying a new style on hover, and then resetting the default style: http://palewi.re/posts/2012/03/26/leaflet-recipe-hover-events-features-and-polygons/ but I'm not sure the right way to do that in react.

As for the style, I'd just start with something like a semi-transparent yellow fill. And then see how that looks.

**Comment by almccon** [comment]
I just realized that I was thinking "projects" not "zones" when I replied to this issue.

We still need a style for the selected project. I think we don't necessarily need a style for the selected zone, but that would be nice too.

Projects can remain visible in the basemap.

**Comment by clhenrick** [comment]
Seems like Zones aren't that important to the user so we shouldn't be concerned with highlighting them. In the site it seems their main purpose is to break up the content for Projects & Open Spaces by geographic area. Not sure if Zones need to be reflected on the basemap, I think it might add more complexity than is needed and ultimately confuse the user.

**Comment by almccon** [comment]
Okay, let's not show zones on the map, and see if we can get away with it. I'm going to hijack this issue to talk about highlighting _projects_ on the map, since we don't have an issue for that.

When you select a project (or even mouseover, probably) the project shape needs to change color, so you see what you've clicked. For example, here I can't tell which shape is Heron's Head Park:

![screen shot 2016-06-28 at 28 jun 11 24 45](https://cloud.githubusercontent.com/assets/1212178/16427614/fc1261a2-3d22-11e6-8809-c43893ef89b2.png)

@clhenrick I'm starting to think that this is more pressing than #150. Do you feel like you can tackle both today?

**Comment by clhenrick** [comment]
okay, I can look into it. Though #150 may be easier to pull off.

**Comment by ericsoco** [comment]
Project highlighting in place, tho needs a visual design pass (colors) 
https://github.com/stamen/bluegreenway/commit/8e1ffcb13e97cb4cb3bca86d51e0643ae593cbd8

**Comment by almccon** [comment]
![screen shot 2016-06-28 at 28 jun 3 29 05](https://cloud.githubusercontent.com/assets/1212178/16435195/05788110-3d49-11e6-8248-1b4e51d435e7.png)

Let's call it good.
