### ISSUE TITLE
Fix the map view for this story, it's squished along the side

### ISSUE THREAD

**Issue by ericrodenbeck** [stamen/bluegreenway#184]
http://stamen.github.io/bluegreenway/#/stories/map/Paddling_on_the_Bay

![screen shot 2016-07-08 at 4 21 15 pm](https://cloud.githubusercontent.com/assets/450233/16704092/10f8e62e-4528-11e6-84f1-3989911d0517.png)

**Comment by emilyhobson** [comment]
This is a rendering bug

**Comment by alecburch** [comment]
happens when you are in a story and switch to map view

**Comment by ericsoco** [comment]
I can't repro this anymore, but I found a bunch of bugs / unimplemented stuff in single story page view that I've since fixed. One was that toggling from page to map view on a story page view was dropping the query string, which is needed to render the story page correctly. So, I think this is fixed, but reopen if not.
