### ISSUE TITLE
Implement grid algorithm for homepage

### ISSUE THREAD

**Issue by ericsoco** [stamen/bluegreenway#39]
quick hit:

Arrange items from lists of 1x1, 1x2, 2x1 across 4-column grid.
Start with most recent item
Iterate over cells in each row
If cell not yet occupied, grab the top item from the next list (e.g. 1x1 -> 1x2 -> 2x1 -> 1x1...)
If cell occupied, move to next

there was more to it, i thought through it lying awake at night once....but that's the starting point.

**Comment by clhenrick** [comment]
@ericsoco I'd rather use a library such as [Masonry.JS](http://masonry.desandro.com/)

**Comment by clhenrick** [comment]
@ericsoco there's a library for this that may work well, [masonry.js](http://masonry.desandro.com/)

**Comment by clhenrick** [comment]
**note to self:** implementing this will require fetching JSON feed data for Stories, Events, and Projects on the homepage load. Concerned about initial load time for this.

**Comment by ericsoco** [comment]
oo, fancy. would like to see how this plays out.

**Comment by clhenrick** [comment]
Actually the library we want to use is called [Packery.JS](http://packery.metafizzy.co/). 

Masonry.js allows for an offset grid but will leave gaps if elements are of different sizes. Packery will do its best to fit all elements so that they're tightly grouped ("...uses a bin-packing algorithm to fill in empty gaps").
