### ISSUE TITLE
Style Projects Polygons GeoJSON overlays

### ISSUE THREAD

**Issue by clhenrick** [stamen/bluegreenway#68]
Make each the same color as the zone underneath, but slightly darker with an outline. Correct me if I'm wrong @alecburch

**Comment by alecburch** [comment]
dew it

**Comment by clhenrick** [comment]
@almccon @alecburch can you plz give me the colors for the BGW Zones?

**Comment by clhenrick** [comment]
@almccon noting that two of the colors you are using for the zones are the same (1 and 4), is that intentional? Copied and pasted from your CartoCSS:

``` less
@color4: #A6CEE3;
@color2: #a6e3a9;
@color3: #a6e3ca;
@color1: #A6CEE3;
```

**Comment by clhenrick** [comment]
To style the Project Polygons as a GeoJSON overlay I need to have a key in the `feature.properties` of each polygon that identifies which zone the polygon resides in. 

@almccon would you mind doing a quick `ST_Intersect()` with the project polygons & zone polygons to assign a `BGW_Zone` property to the former?

**Comment by almccon** [comment]
The colors were mainly meant to be different from adjacent zones, not distinct across the zones. Why I didn't alternate color 1 color 2 color 1 color 2 I have no idea.

And yup I can add a `BGW_Zone` to the polygons.

**Comment by almccon** [comment]
Ugh. I was have geometry errors trying to do the `ST_Intersects()`, and it was taking me too long to figure out where the errors were.

So it was quicker just to manually add the zones for each project based on how they're listed in the spreadsheet: https://docs.google.com/spreadsheets/d/1HIRLc2usDhXLP_a9nbboAaalNiHga4lGt025616TI0k/edit#gid=406674860

And guess what, some of the projects fall in the wrong zone if I do it that way. For example, Pier 94 is in the "Pier 70" zone according to the spreadsheet, but according to the rough zones I drew based on the information in #10.

Some of the errors might be my fault (the polygons are a mixture of shapes derived from various files, plus some shapes drawn by me), but I think mostly they just require clarification.

Soooo... I'm using the spreadsheet as the source of truth, so @clhenrick things might look a little weird. But at least this way we will force ourselves to resolve the question with feedback from the client.

![screen shot 2016-05-27 at 27 may 7 31 50](https://cloud.githubusercontent.com/assets/1212178/15624638/db7c922c-2441-11e6-8731-2588d349e001.png)

Also note, @clhenrick I used your zone shortcodes for the `BGW_Zone` field instead of the full names.

**Comment by almccon** [comment]
So, the new plan, as far as I understand it, is to use two colors to indicate Projects vs Open Spaces (see #61). If so, we should close this in favor of that.

**Comment by ericsoco** [comment]
Closing in favor of #61.
